# Generated by Django 4.1.2 on 2022-10-06 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Imagine',
        ),
    ]
